# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    
    - name: templ-generator-action
      # uses: capthiron/templ-generator-action@f1f7b5d0b261eccff32fa3fc17cf563d993fee94
      uses: capthiron/templ-generator-action@v1    
      with:
        # The directory where to look for .templ files.
        directory: "./internal/views"
        # Flag to enable or disable committing changes.
        commit: false
        # Flag to enable or disable setting up Go.
        # using default (true)
        # The Go version to use.
        go-version: '1.23.x'
        # The templ version to use.
        # using default (latest)

    - name: Build
      run:
        go build ./cmd/server/main.go
      env: 
        GH_TOKEN: ${{ secrets.WORK_KEY }}
    
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: wokflow_gen
