# This workflow will build a golang project
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        token: ${{ secrets.WORK_KEY }}
    
    - name: templ-generator-action
      uses: capthiron/templ-generator-action@v1    
      with:
        # The directory where to look for .templ files.
        directory: "./internal/views"
        # Flag to enable or disable committing changes.
        # with build after this, use as incremental
        commit: True
        # Flag to enable or disable setting up Go.
        # using default (true)
        # The Go version to use.
        go-version: '1.23.x'
        # The templ version to use.
        # using default (latest)

    - name: Build
      run:
        go build ./cmd/server/main.go
    
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: wokflow_gen
